
project_id = "xnxpwdnwsolkstyatwld"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.generate-shipping-label]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
