name: Build & Deploy Credit Clarity

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Production Build
    runs-on: ubuntu-latest
    env:
      # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      # VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

    steps:
      - name:  Checkout Code
        uses: actions/checkout@v4

      - name:  Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name:  Install Dependencies
        run: npm ci

      - name:  Build with Vite
        run: npm run build

      # - name: "Optional: Run Tests"
      #   run: npm test
      #   continue-on-error: true # Remove this if test failures should block deployment

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name:  Checkout Code
        uses: actions/checkout@v4

      - name:  Install Vercel CLI
        run: npm install -g vercel

      - name:  Deploy to Vercel
        run: |
          echo "🚀 Deploying to Vercel..."
          vercel deploy --prod --yes \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --org-id ${{ secrets.VERCEL_ORG_ID }} \
            --project-id ${{ secrets.VERCEL_PROJECT_ID }}
